---

 - hosts: localhost
   become: true
   tasks:
     - name: check PHP is installed or not
       command: php -v
       register: php_installed
       ignore_errors: true

     - debug: var=php_installed

     - name: php_installed
       debug: msg='php is installed'
       when: php_installed|success

     - name: php not installed
       debug: msg='php is snot installed'
       when: php_installed|failed
 
